### ISSUE TITLE
JS Modules for components

### ISSUE THREAD

**Issue by thien-do** [axieinfinity/festival#1]
When designing and using [React components](https://reactjs.org/docs/components-and-props.html#function-and-class-components), we usually need to [export](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export) and [import](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/import) more than just the component itself. For example, we may want to import the [interface](https://www.typescriptlang.org/docs/handbook/interfaces.html) of a prop (e.g., button's color) or its implementations/options (e.g., the "primary" color for a button).

This page describes our expectations, several approaches, and what we believe is the optimal solution to export and import React components as JS modules (for now).

# Expectations

We should choose an approach that:

- Increase the discoverability of a component (e.g., what props are there and what are their options).
- Increase the ease for a new engineer to understand the approach (i.e., it's not too far/strange from the outside world).
- Decrease naming conflicts when importing props with same name from several components (e.g., button's color and tag's color).

# Approaches

Although there are only 2 types of export in JavaScript (default and named), there are [many ways](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export#Syntax) (in term of syntax) to export and import from a module. Here we only discuss the most prominent ones:

## A. All are named without prefix

```tsx
// Button.ts
export interface Color { light: string; dark: string; }
export const Colors: { [key: string]: Color } = { /* ... */}
export const Component = ({ color: Color }) => (/* ... */);
```

```tsx
// Foo.tsx
import * as Button from "@dvkndn/core/button";
import * as Tag from "@dvkndn/core/tag";
<Button.Component color={Button.Colors.Primary} />
```

## B. All are named with prefix

```tsx
// Button.ts
export interface ButtonColor { light: string; dark: string; }
export const ButtonColors: { [key: string]: Color } = { /* ... */ };
export const Button = ({ color: Color }) => (/* ... */);
```

```tsx
// Foo.tsx
import { Button, ButtonColors } from "@dvkndn/core/button";
import { Tag, TagColors } from "@dvkndn/core/tag";
<Button color={ButtonColors.Primary} />
```

## C. Component is default, others are named without prefix

```tsx
// Button.ts
export interface Color { light: string; dark: string; }
export const Colors: { [key: string]: Color } = { /* ... */ };
export default ({ color: Color }) => (/* ... */);
```

```tsx
// C1. Alias import
// Foo.tsx
import Button, { Colors as ButtonColors } from "@dvkndn/core/button";
import Tag, { Colors as TagColors } from "@dvkndn/core/tag";
<Button color={ButtonColors.Primary} />
```

```tsx
// C2. Namespace import
// Foo.tsx
import Button, * as button from "@dvkndn/core/button";
import Tag, * as tag from "@dvkndn/core/button";
<Button color={button.Colors.Primary} />
```

# Current solution

- Speaking of discoverability, A is better than B and C:
    - In A, users can see all exports at every occurrence of `Button`
    - In B and C1, the exports can only be suggested at the import statement. The "auto import" of some editors may not be able to help here (to discover ButtonColors).
    - in C2, exports may be found at occurrences of `button` but this is obviously not as good as A
- Speaking of learning curve, C is the most common approach.
    - A and B are less common because in most systems the API of components are quite simple and only export the component itself.
    - However, these are all standard methods and any engineer should be able to understand how they work in no time.
- Speaking of naming in importing, both A and B are better than C:
    - A is good because of the enforcement of namespace imports, having a nice, concise import statements.
    - B is good because all definitions are globally unique in the first place, thus make the import easier, but could easily lead to long, repetitive import statements (e.g., `import { FooA, FooB, ..., FooX }`).
    - C is not really good as users must always do extra work to avoid naming conflicts, either via alias or via namespace (more work comparing to A).

**Therefore, for now, we prefer the approach A.**

# References

- [https://create-react-app.dev/docs/importing-a-component](https://create-react-app.dev/docs/importing-a-component)
- [https://exploringjs.com/impatient-js/ch_modules.html](https://exploringjs.com/impatient-js/ch_modules.html)

**Comment by nhducit** [comment]
![image](https://user-images.githubusercontent.com/4246176/63336293-21f1fc00-c369-11e9-8c09-dd6c52941a6b.png)

**Comment by nhducit** [comment]
in option B
```
export const Button = ({ color: Color }) => (/* ... */);
should be
export const Button = ({ color }:{ color: Color }) => (/* ... */);

```

**Comment by thien-do** [comment]
Thanks, did not know that

**Comment by thien-do** [comment]
Actually I'm turning this into files
